### PR TITLE
Update the OpenAPI specification and bundled data

### PR DESCRIPTION
**Pull request by foresthu-stripe**
r? @dpetrovics-stripe

### CODE REVIEW

**Comment by brandur-stripe** [comment]
@foresthu-stripe Just out of curiosity, what's the main change you're trying to bring in?

**Comment by foresthu-stripe** [comment]
@brandur-stripe I'm trying to add the new `cancel` endpoint for top-ups to APIs for other languages

**Comment by brandur-stripe** [comment]
Cool, thanks!

LGTM.

**Comment by brandur-stripe** [comment]
Released as 0.25.0.

**Pull request merged**
