### PR TITLE
Refactor project to use go modules and move the server inside of a new package.

### LINKED ISSUE #206: Refactor to make stripe-mock useable as a package
It would be great to be able to embed `stripe-mock` as a package in Go. For example, something like:
```go
package abc

import (
   "testing"
   "stripe/stripe-mock"
)

func TestMyApp(t *testing.T) {
   mock := stripe.RunMock()
   defer mock.Stop()

   // perform tests against stripe-mock here
}
```

In order to make this work, probably two changes are required:
- Move the bulk of the functionality out of `package main`. This could be accomplished either by moving most of the functionality in `github.com/stripe/stripe-mock` to another package in a sub-folder, or moving `package main` into a sub-folder (e.g., `github.com/stripe/stripe-mock/stripe-mock`). The former is probably preferred because no change would be required to anyone who has `go get -u github.com/stripe/stripe-mock` in their tooling.
- Go modularize `stripe-mock` (i.e., `go mod init` => `go.mod`, `go.sum`).

### PR DESCRIPTION
**Pull request by Splizard**
The minumum work to fix #206

Now the server can be embedded inside of a Go project and integrated
with `go test`

Go generating the project directory bundles the certificates for main and the openapi data is now placed in the spec package which also houses the test data.

The project has been updated to use Go modules instead of the legacy Vendoring and I have updated the necessary tooling.

Some ideas that popped up while I wrote this (to cleanup the project):
- Move the certificate bundle and listener into the server package.
- Merge the server and spec packages together, so that testing functions don't need to be exported (stripetest package?).
- Have this repo or the stripe-go repo recognise the other with a simple way to enable the mock server for testing (ie in the way that #206 suggests)

### CODE REVIEW

**Comment by supermarin** [comment]
@richardm-stripe @remi-stripe is there any interest from Stripe to get this merged?

**Comment by jhartman86** [comment]
this would be reaaaal nice to have for us gophers out there. any chance of seeing this ever get merged in?

**Comment by jhartman86** [comment]
Bump on this request to the maintainers. This would make it so, so much nicer to work with.

**Comment by Splizard** [comment]
@jhartman86 in the meantime, you can use my fork https://github.com/Splizard/stripe-mock

```
replace github.com/stripe/stripe-mock => github.com/splizard/stripe-mock v0.98.0
```

The following code is enough to get stripe mocked for unit testing.
```go
func MockStripe() {
	b := stripe.NewBackends(&http.Client{})
	b.API = stripe.GetBackendWithConfig(
		"api",
		&stripe.BackendConfig{
			HTTPClient: http.DefaultClient,
			URL:        stripe.String("http://localhost:12111"),
		},
	)

	//Setup stripe
	stripe.SetBackend("api", b.API)
	stripe.Key = "sk_test_123"

	// For both spec and fixtures stripe-mock will by default load data from
	// internal assets compiled into the binary, but either one can be
	// overridden with a -spec or -fixtures argument and a path to a file.
	stripeSpec, err := spec.LoadSpec("")
	if err != nil {
		panic(err.Error())
	}

	fixtures, err := spec.LoadFixtures("")
	if err != nil {
		panic(err.Error())
	}

	stub, err := server.NewStubServer(fixtures, stripeSpec, false)
	if err != nil {
		panic(fmt.Sprintf("Error initializing router: %v\n", err))
	}

	httpMux := http.NewServeMux()
	httpMux.HandleFunc("/", stub.HandleRequest)

	// Deduplicates doubled slashes in paths. e.g. `//v1/charges` becomes
	// `/v1/charges`.
	handler := &server.DoubleSlashFixHandler{Mux: httpMux}

	go http.ListenAndServe(":12111", handler)
}
```

**Comment by akalinin-stripe** [comment]
The changes have been merged as part of #265, which required resolving the conflicts. Thanks for doing the bulk of the work on this @Splizard

**Pull request closed without merging**
