### PR TITLE
Use embed instead of bindata

### PR DESCRIPTION
**Pull request by pakrym-stripe**
GO has a native way of embedding files. Avoids having to run extra command to update specs.

### CODE REVIEW

**Review by akalinin-stripe — APPROVED** [review]
Looks like a good change.

**Comment by pakrym-stripe** [comment]
I also checked the resulting file size, it went down by 400KB.

**Comment by pakrym-stripe** [comment]
I'll update https://confluence.corp.stripe.com/display/DEVX/Releasing+stripe-mock when this goes in.

**Review by dcr-stripe — COMMENTED** [review]
This looks good - thanks Pavel! Just to double check - how does this work when making a binary? Will `go:embed` bundle the file(s) into the binary like `go bindata` was doing?

**Comment by pakrym-stripe** [comment]
> Will go:embed bundle the file(s) into the binary like go bindata was doing?

Yes, `go:embed` is a native replacement for `go bindata` was doing.

**Review by dcr-stripe — APPROVED** [review]
LGTM! Thanks Pavel - great stuff.

Ran a local test where I pulled branch, built using `make`, copied over the executable to an isolated folder, and all worked well.

**Pull request merged**
